import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { headers } from "next/headers";
import { getAppData } from "@/lib/api";
import type { App } from "@/lib/types";
import { ToastProvider } from "@universe-platform/ui";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function OrgNavLink({ title, href }: { title: string; href: string }) {
  return (
    <li>
      <Link
        href={href}
        className="px-4 py-2 rounded-md text-slate-200 hover:text-white hover:bg-white/10 transition-colors text-sm font-medium inline-block"
      >
        {title}
      </Link>
    </li>
  );
}

function Navbar({ appData }: { appData: App }) {
  const sortedPages = [...appData.pages].sort((a, b) => a.order - b.order);
  const initial = appData.organization.name ? appData.organization.name[0].toUpperCase() : "U";

  return (
    <header className="h-16 bg-panel-dark text-white flex items-center justify-between px-6 border-b border-neutral-800 shrink-0">
      <div className="flex items-center gap-6">
        <div className="flex items-center gap-3 font-bold text-xl">
          <div className="w-8 h-8 rounded-full bg-brand text-white flex items-center justify-center font-bold text-sm shrink-0">
            {initial}
          </div>
          <span className="text-white tracking-wide font-bold">{appData.organization.name}</span>
        </div>
        <nav>
          <ul className="flex items-center gap-1">
            {sortedPages.map((page) => (
              <OrgNavLink key={page.id} title={page.pageName} href={`/${page.slug}`} />
            ))}
          </ul>
        </nav>
      </div>
    </header>
  );
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const host = headersList.get("host") ?? "";
  const appData = await getAppData(host);

  if (!appData) {
    return (
      <html lang="he" dir="rtl" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
        <body className="min-h-full flex items-center justify-center bg-slate-50 text-slate-900">
          <div className="p-10 text-center text-xl">App not found</div>
        </body>
      </html>
    );
  }

  return (
    <html
      lang="he"
      dir="rtl"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-slate-50 text-slate-900">
        <ToastProvider>
          <Navbar appData={appData} />
          <main className="flex-1 flex flex-col">
            {children}
          </main>
        </ToastProvider>
      </body>
    </html>
  );
}
