import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { headers } from "next/headers";
import { getAppData } from "@/lib/api";
import type { App } from "@/lib/types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function OrgSidebarLink({ title, href }: { title: string; href: string }) {
  return (
    <li>
      <Link
        href={href}
        className="block px-4 py-2 rounded-md bg-white/5 text-brand hover:bg-white/10 transition-colors text-right"
      >
        {title}
      </Link>
    </li>
  );
}

function Sidebar({ appData }: { appData: App }) {
  const sortedPages = [...appData.pages].sort((a, b) => a.order - b.order);

  return (
    <aside className="w-64 bg-panel-dark text-white flex flex-col border-l border-neutral-800 shrink-0">
      <div className="h-16 flex items-center justify-end px-6 font-bold text-xl text-brand border-b border-neutral-800">
        {appData.organization.name}
      </div>
      <nav className="flex-1 p-4">
        <ul className="space-y-2">
          {sortedPages.map((page) => (
            <OrgSidebarLink key={page.id} title={page.pageName} href={`/${page.slug}`} />
          ))}
        </ul>
      </nav>
    </aside>
  );
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const host = headersList.get("host") ?? "";
  const appData = await getAppData(host);

  if (!appData) {
    return (
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
        <body className="min-h-full flex items-center justify-center">
          <div className="p-10 text-center text-xl">App not found</div>
        </body>
      </html>
    );
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="flex flex-row-reverse min-h-screen bg-slate-50 text-slate-900">
          <Sidebar appData={appData} />
          <main className="flex-1 flex flex-col">
            <header className="h-16 bg-white border-b border-slate-200 flex items-center justify-between px-6 flex-row-reverse"></header>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
